### ISSUE TITLE
Angular naming conventions broken by using $event

### ISSUE THREAD

**Issue by radarfox** [toddmotto/angular-styleguide#135]
Hello Todd,

I think you have broken Angular naming conventions by suggesting:

* Use `$event` as a function argument in the parent method
* Pass an `$event: {}` Object back up from a stateless component

On the [root doc page](https://docs.angularjs.org/api) there is the warning: "Angular Prefixes $ and $$: To prevent accidental name collisions with your code, Angular prefixes names of public objects with $ and names of private objects with $$. Please do not use the $ or $$ prefix in your code."

This name is already used in [ngClick and ngFocus directive](https://docs.angularjs.org/guide/expression#-event-) so you collide with that.

Dollar named scope objects also has some [tricky differences](http://stackoverflow.com/questions/12648543/angularjs-and-its-use-of-dollar-variables).

Do you care? :)

**Comment by toddmotto** [comment]
Hello radarfox! So, `$event` is actually part of Angular, for instance:

```html
<form ng-submit="$ctrl.onSubmit($event, $ctrl.payload);">
```

All I'm doing here is creating my own "fake"/custom event Object to pass back up. This way, the `$event` is being replaced by our own custom event, instead of an Angular/DOM event of some kind. This method mirrors the Angular 2 `EventEmitter` syntax when binding to an `@Output()` decorator. Hope this helps - will close this issue off :)

**Comment by radarfox** [comment]
And because it "is actually part of Angular" you shouldn't bind custom events on the same name to "prevent accidental name collisions with your code".

Simple `event` without the $ would do the same job and without shadowing native Angular objects and making them inaccessible.

**Comment by toddmotto** [comment]
It was actually Pete Bacon Darwin that suggested to me using `$event`, and given he's the Angular 1.x project lead, I'm content with that advice :)
