### ISSUE TITLE
Directory structure 

### ISSUE THREAD

**Issue by LucasCaixeta** [toddmotto/angular-styleguide#40]
What are your best practices for directory structure?
Could you show for us? 
I´m using this: https://github.com/vngrs/ng-simple/tree/master/app

**Comment by mtpultz** [comment]
Hi @LucasCaixeta, there are a lot of different ways that people layout their folder hierarchy.  Originally it was something like:

/controllers
/directives
/services

But if your application needs to be scalable this will cause lots of growing pains.  So others have adopted structures that nest based on the URL or based on your understanding of the UI, which I'll outline below in 3 points:

1. Assuming basing your folder structure on URL is self explanatory I'll just say the amount of folders you have will balloon.

2. Using the UI you can split your folders into the below structure where a major feature might be tabs and minor features are the tabbed content with associated component folders.  Arguably adding your services into the feature folders might be a bad idea, especially if they cross cut components, so you could add them to a /services folder in the root so you can actually find them and so services aren't written that already exist.  Each feature gets its own appjs and is subsequently required by your mainJS.

```
/major-feature-1
  /minor-feature-1
    controller.js
    directive.js
    service.js
  /minor-feature-2
  ...etc
/services
  cross-cutting-service1.js
  cross-cutting-service2.js
```

1. Another take on the last example is using the pages of the application as the folder, which contains the components with their own files, but where services that crosscut are also placed in the root maybe even in a /common folder instead of just /services.  Each page gets its own appjs and is subsequently required by your mainJS.

```
/page
  /component
    controller.js
    directive.js
    service.js
/common
  /services
    cross-cutting-service1.js
    cross-cutting-service2.js
```

These are examples of all the ways I've read about and have evolved to use, but I'd be interested to know what others have to say with regards to the style guide.  Either with other examples and why they are better or tweaks to one of the offered solutions.

Cheers

**Comment by toddmotto** [comment]
Closing off as this is now in the new styleguide which has been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).
