### ISSUE TITLE
About components and common module...

### ISSUE THREAD

**Issue by ctaepper** [toddmotto/angular-styleguide#60]
i thought about those modules while working on the other PR yesterday. you are not really explaining the purpose of those modules, other that *one single place to inject component modules*.

however, is this really best practice? lets take the `common/footer` component for example. you inject it via the common module into the root module, so the footer module is available throughout the whole app, i can use this component everywhere, for examples sake i use it now in my (view-) component called `home` which represents the initial view of my app. now, i want to test my `home` component in isolation. this component now no knowledge about the `common/footer` component, because you didn't explicitly inject the dependency into the module definition for `home`, but rely on the module being injected into the root module...

in our setup, we import and inject every single module that is required by the current module. at first, it seems like a bit of overhead, but this way, we always have all necessary dependencies available, when testing a module in isolation.

**Comment by floriangosse** [comment]
We do the same in our applications: every module requires the modules which are needed and don't relay on the app module. In our app/root module we only require the routed components.

**Comment by jcarroll2007** [comment]
+1

**Comment by toddmotto** [comment]
High level modules just act as containers/imports. Nothing else.

Imports:

`app`
`common`
`components

These are just names for the "structure" of the modules. Each module then imports a specific module. It's just a nice way to break things down without colliding them altogether, as well as a "modular" way to visualise what's happening and where each of your feature modules is meant to go. Hope that helps, if not feel free to keep commenting, will close off otherwise :)
