### ISSUE TITLE
[Question] Typescript specifc remarks / info?

### ISSUE THREAD

**Issue by AkosLukacs** [toddmotto/angular-styleguide#69]
Hey Todd, 
What would be your opinion about including some typescript related info into you guide? 
If PRs are welcome, should those be included as a new chapter, or inline? I guess a new chapter would be less disturbing overall, but easier to miss...

**Comment by mcranston18** [comment]
Though this might be beyond the scope of the question, I'd be curious to hear thoughts on whether TypeScript is even integral to good Angular 1.5/2 code. This style guide obviously doesn't use TS so does that mean it recommends not using it if a dev is about to start a new Angular project?

**Comment by toddmotto** [comment]
@AkosLukacs Hey! So, I think a TypeScript version would be extremely awesome. What do you think to the following directory structure:

```
- readme.md (main readme - points to the other guides giving user the choice)
- es2015/
      readme.md
  i18n/
      es-es.md
- typscript/
      readme.md
  i18n/
      es-es.md
```

The `readme.md` would simply 

@mcranston18 It's not included in the guide because I don't feel it's up to me to decide whether you/your team should use TypeScript (similarly with Angular 2, however it may be advised for Angular 2).

**Comment by floriangosse** [comment]
@AkosLukacs @toddmotto maybe the styleguide of Airbnb is an inspiration: https://github.com/airbnb/javascript

**Comment by toddmotto** [comment]
Closing this one as @laskoviymishka has made a PR.
