### ISSUE TITLE
Directive Class Injection

### ISSUE THREAD

**Issue by jared-christensen** [toddmotto/angular-styleguide#78]
I'm having problems injecting $timeout into the directive class. I followed the guide can someone double check the guide for me?

Update: I think there are some answers in here: https://github.com/michaelbromley/angular-es6/blob/master/src/app/utils/register.js

**Comment by miguelCT** [comment]
I was about to open an issue about this to ask some questions.

Firstly, thanks Todd for the great and clear styleguide.
Looking at the issue, this is Todd's Directive with class example:

 
```js
/* ----- todo/todo-autofocus.directive.js ----- */
import angular from 'angular';

class TodoAutoFocus {
  constructor() {
    this.restrict = 'A';
  }
  link($scope, $element, $attrs) {
    $scope.$watch($attrs.todoAutofocus, (newValue, oldValue) => {
      if (!newValue) {
        return;
      }
      $timeout(() => $element[0].focus());
    });
  }
}

TodoAutoFocus.$inject = ['$timeout'];

export default TodoAutoFocus;

```

Maybe I'm missing something but I'll try to explain myself.

#### Issue 1
When the ```$timeout``` is injected to the class, I suppose the same dependency should be passed as parameter in the class constructor, and assigned to ```this``` in order to be used in the prototype functions, in this case, **link function**. 
```js
constructor($timeout) {
  this.restrict = 'A';
  this.$timeout = $timeout;
}
link($scope, $element, $attrs) {
    [...]
        this.$timeout(...);
    [...]
}
```
This should work in the same way same as it does in controller or service pattern, in spite of that, when the directive is linked and the link function is executed, the value of ```this``` is undefined. 
I've read some articles, and [this one](http://www.michaelbromley.co.uk/blog/350/exploring-es6-classes-in-angularjs-1-x) in particular says:
>[...] when Angular invokes the link function, it is no longer in the context of the class instance, and therefore this.$interval will be undefined.

**->** So, how it should be done to use the dependency inside the link function in a clean way?

#### Issue 2
And the other doubt is, when the directive is declared, despite doing the ```TodoAutoFocus.$inject = [...]``` in the class file, if you don't pass the explicit dependency to the angular directive declaration, it won't be available in the class constructor. 

**->** Is it correct?
```js
angular.module (...)
.directive('wrAutoFocus', ['$timeout', ($timeout) => new AutoFocus($timeout)])
```

The Directive pattern with **es6 const is working fine** though, so I think Angular is not working right with es6 classes for directives, and the same issue happens with factories as Todd has pointed.

I hope Todd could throw some light on this,
Thanks in advance.

**Comment by d3lm** [comment]
Another way of injecting a service such as `$timeout` is to add your dependency to your constructor and use a static property called `$inject` as follows:

```
class Foo implements ng.IDirective {
  static $inject: Array<string> = ['$timeout'];
  constructor(private $timeout: ng.ITimeoutService) { }
  ...
}
```

Or you use something like ngAnotate. With this however, you will be implicitly writing your dependencies. This also requires another build step.

```
class Foo implements ng.IDirective {
  constructor(private $timeout: ng.ITimeoutService) { 
    'ngInject';
  }
  ...
}
```

**Comment by miguelCT** [comment]
Ok, I get your point on the first issue (at least I think, I don't know very much about Typescript). 
So in JS, do you mean doing something like this? (or instead a ```let``` using a ```weakMap```)
```js
let $timeout = null;
class AutoFocus {
    constructor(_$timeout_) {
        this.restrict = 'A';
        $timeout = _$timeout_;
    }
    link($scope, $element, $attrs) {
        [...]
        $timeout(...);
        [...]
    }
}
```

In this case it works, but I don't feel it very clean because it'd mean having a different way of using the dependencies comparing it to the other patterns. I think I would prefer using **const pattern** instead of this way. 

And about ngAnotate, I agree it is a cool tool, but for now, in my team, we're doing the injection by ourselves. We'll include it when we feel every ES6 pattern for AngularJS artifacts are clear and stable.

**Comment by d3lm** [comment]
@miguelCT Even though I am using TypeScript, I think you can still use the static property without the type annotation.

**Comment by miguelCT** [comment]
@d3lm You're right, in es6 it can be done something like this:

```js
class AutoFocus {
    constructor() {
        [...]
    }
    static get $inject () {
        return ["$timeout"];
    }
}
```

But this not solves the problem if you don't include the dependency in the angular.directive declaration: ```angular.directive('name', ['$timeout', ($timeout) => new AutoFocus($timeout)]))```.

Finnally, we've decided to use the other pattern for directives as we don't find the class pattern perfectly suited for AngularJs directives and its dependency injection.

**Comment by AkosLukacs** [comment]
Actually 
```javascript
class SomeDirective implements ng.IDirective {
  public static directiveName = 'someDirective';
  public static $inject: string[]= ['$log'];
  constructor($log: ng.ILogService){ /* ... returns the directive definition object ... */ }
}

myModule.directive(SomeDirective.directiveName, <any>SomeDirective);
```
works just fine in TypeScript. 
Note, that the `$inject` is not a getter, and the directive class itself is casted to `<any>`, because the type definition expects a `DirectiveFactory`. It doesn't feel perfect, but works...

**Comment by d3lm** [comment]
@AkosLukacs @miguelCT Exactly. It's not supposed to be a getter, it's just a public static member of your class. However, @miguelCT is right that ES6 classes can only hold functions and no variables. So as he proposed, you must write a function which returns the array and I think this doesn't work. So for ES6 I think you must stick to the `$inject`.

**Comment by miguelCT** [comment]
@AkosLukacs @d3lm Yes, as @d3lm said, in ES6 there's no way (at least that I know) of declaring a static property directly, but I think declaring a *static getter* is not completely wrong (and it works for $inject).

I mean, when you declare a *getter* of a variable *X* in an ES6 class, you'll end with an pseudo-property *X* in the instance prototype , so when you declare a *static getter* you'll end with an *X* pseudo-property in the Class. Maybe it's not the most clean way, but I think is one of the workarounds in order to be able to declare static properties using only ES6 syntax.

Maybe I'm wrong trying to do everything inside a Class, but I feel mixing ES5 and 6 in the same Class definition is not very clean.

**Comment by d3lm** [comment]
@miguelCT Exactly. But it's close to the static $inject property as you do with TypeScript.

**Comment by miguelCT** [comment]
@d3lm Yeah, I agree with you that AngularJs Directives don't feel perfectly right with ES6 classes (the same happens with Factories), so I'll stick to the other pattern and avoid using Classes with Directives.

**Comment by jared-christensen** [comment]
What do you think about this idea...
http://stackoverflow.com/a/33714913/330191
