### ISSUE TITLE
Good place for services (generic) and sass variables and generic files ?

### ISSUE THREAD

**Issue by ianjohnspain** [toddmotto/angular-styleguide#94]
Hi,

I have started storing my scss files with their component. Seems logical, is that the direction everyone is taking ?

Then popped up a question, what about scss variables and generic files that have no place within a component ? And what about services that are global i.e. shared between components are not specific to any component. 

I am storing (as per the guide) services for a specific component with there component - a good example is the todo component which has a todo service but things like shared services, constants - a good place for these ?

Also initially i was placing the specs (tests) along side the components but now I am considering creating a sub directory called tests - good idea ? Reason behind this logic is that i could have a number of spec files,  1 for the controller, 1 for the component and 1 (or more) for the component specific service.

I would really like anybodies input on the above.

Sharing ideas can only improve  what we have so far :-)

**Comment by mcranston18** [comment]
Good question, I'd also be interested in hearing how others handle this. Here's my approach:

1. For SASS/CSS files, I have a `styles` folder in the root folder which handles global style concerns and then I also have `_style.scss` files inside component folders where needed. 

```
├── app/
│   ├── components/
│   │  ├── calendar/
│   │  │  ├── index.js
│   │  │  ├── _style.scss
│   │  ├── alerts/
│   │  │  ├── index.js
│   │  │  ├── _style.scss
│   ├── styles
│   │  ├── _button.scss
│   │  ├── _lists.scss
│   │  ├── _tables.scss
│   │  ├── _typographs.scss
│   ├── index.scss
```
My justification for putting a `buttons.scss` or ` lists.scss` file in the generic `/styles` folder is because these don't really belong to a single component. There could be several components that use the `.list` styling.

2. For global services and constants, I use the same pattern:
```
├── app/
│   ├── components/
│   │  ├── calendar/
│   │  │  ├── index.js
│   │  │  ├── _style.scss
│   │  ├── alerts/
│   │  │  ├── index.js
│   │  │  ├── _style.scss
│   ├── services
│   │  ├── utilities.js
│   ├── constants
│   │  ├── provinces.js
│   │  ├── states.js
```

3. For your tests, I think it's ultimately up to you. If you prefer to put your tests in a folder called `/tests` and you do so consistently, I don't see much of a difference. I think the approach as per the style guide would probably recommend something like:
```
├── app/
│   ├── components/
│   │  ├── calendar/
│   │  │  ├── index.js
│   │  │  ├── calendar.controller.js
│   │  │  ├── calendar.controller.spec.js
│   │  │  ├── calendar.component.js
│   │  │  ├── calendar.service.js
│   │  │  ├── calendar.service.spec.js
```
But I would let @toddmotto be the judge of that.

**Comment by chrisjlee** [comment]
I see this no different than how one manages js files:

- Global code/styles go in the base folder
- component dependent code/styles goes in the component folder

So i would concur with @mcranston18 approach.

**Comment by noderat** [comment]
My implementation is similar. However, I use `calendar.stylesheet.scss` to follow the naming convention outlined in the guide.
